# These are supported funding model platforms

github: []
patreon: awais786327
open_collective: awais786327
ko_fi: awais786327
community_bridge: goclean
liberapay: awais786327
issuehunt: awais786327
otechie: awais786327
custom: []
